# .cirrus.yml
task:
  build:
    docker:
      image: python:3.9  # Use a Python 3.9 Docker image
    steps:
      - install_packages:
          script:
            - pip install -r requirements.txt  # Install dependencies
      - run_tests:
          script:
            - pytest tests/  # Run tests in the tests directory

  # Optional: Another task for testing with Python 3.8
  test_python_3.8:
    docker:
      image: python:3.8  # Use a Python 3.8 Docker image
    steps:
      - install_packages:
          script:
            - pip install -r requirements.txt  # Install dependencies
      - run_tests:
          script:
            - pytest tests/  # Run tests in the tests directory

notifications:
  email:
    - your_email@example.com  # Add your email for notifications
