# .cirrus.yml
# Cirrus CI configuration for Python testing using Ubuntu 22.04

task:
  name: Python Test
  container:
    image: ubuntu:22.04  # Use Ubuntu 22.04 as the container image
  language: shell  # Specify the language as shell
  install_script:
    - apt-get update  # Update the package list
    - apt-get install -y python3 python3-pip  # Install Python and pip
    - pip3 install -r requirements.txt  # Install Python dependencies
  script:
    - echo "Running tests..."  # Placeholder for starting message
    - pytest tests/  # Run tests located in the tests directory
    - echo "Tests completed."  # Completion message

# Notifications
notifications:
  email:
    - your_email@example.com  # Add your email for notifications
